--ADICONANDO O CAMPO CATEGORIA 
--NA TABELA DE CLIENTE

ALTER TABLE CLIENTE 
ADD CATEGORIA INT NOT NULL DEFAULT 1;
GO

--CRIANDO UMA REGRA PARA O PREENCHIMENTO
--DO CAMPO CATEGORIA

ALTER TABLE CLIENTE
ADD CONSTRAINT CHECK_CATEGORIA
CHECK (CATEGORIA IN (1,2,3,4));
GO